modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues_url}"
logoFile="${mod_id}_icon.png"
logoBlur=false
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${sources_url}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[modproperties.${mod_id}]
catalogueImageIcon="${mod_id}_icon.png"